export const matrix = {
  contracts: 'Contract',
  temas: 'Tema',
  states: 'State',
  types: 'Type',
  positions: 'Position',
  departments: 'Department',
  subdivisions: 'Subdivision',
  currentPositions: 'CurrentPosition',
  extCurrentPositions: 'ExtCurrentPosition',
  employees: 'Employee',
  extEmployees: 'ExtEmployee',
  extIncomings: 'ExtIncoming',
  extOutgoings: 'ExtOutgoing',
  intIncomings: 'IntIncoming',
  intOutgoings: 'IntOutgoing',
  internals: 'Internal',
  incNumbers: 'IncomingNumber',
  intIncNumbers: 'IntIncomingNumber',
  internalIncNumbers: 'InternalIncomingNumber',
  extIncFiles: 'ExtIncFile',
  extOutFiles: 'ExtOutFile',
  intIncFiles: 'IntIncFile',
  intOutFiles: 'IntOutFile',
  internalFiles: 'InternalFile',
  extIncStates: 'ExtIncState',
  intIncStates: 'IntIncState',
  internalIncStates: 'InternalIncState',
  resolutions: 'Resolution'
}
export const entity = [
  'contracts',
  'temas',
  'organisations',
  'states',
  'types',
  'positions',
  'departments',
  'subdivisions',
  'currentPositions',
  'extCurrentPositions',
  'employees',
  'extEmployees',
  'extIncomings',
  'extOutgoings',
  'intIncomings',
  'intOutgoings',
  'internals',
  'incNumbers',
  'intIncNumbers',
  'internalIncNumbers',
  'extIncFiles',
  'extOutFiles',
  'intIncFiles',
  'intOutFiles',
  'internalFiles',
  'extIncStates',
  'intIncStates',
  'internalIncStates',
  'resolutions'
]
